### ISSUE TITLE
Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced. while reading data from contract. Private ETH Blockchain

### ISSUE THREAD

**Issue by pawanlapits** [ethereum/ethereum-org-website#3180]
Hi Team, 

I am able to write data into smart contract wi thout any issue but when i want to fetch that data from contract,i am getting below error : 

Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at ABICoder.decodeParametersWith (/home/ubuntu/projects/zeroid/server/node_modules/web3-eth-abi/lib/index.js:298:15)
    at ABICoder.decodeParameters (/home/ubuntu/projects/zeroid/server/node_modules/web3-eth-abi/lib/index.js:285:17)
    at Contract._decodeMethodReturn (/home/ubuntu/projects/zeroid/server/node_modules/web3-eth-contract/lib/index.js:470:22)
    at Method.outputFormatter (/home/ubuntu/projects/zeroid/server/node_modules/web3-eth-contract/lib/index.js:760:42)
    at Method.formatOutput (/home/ubuntu/projects/zeroid/server/node_modules/web3-core-method/lib/index.js:147:54)
    at sendTxCallback (/home/ubuntu/projects/zeroid/server/node_modules/web3-core-method/lib/index.js:523:33)
    at /home/ubuntu/projects/zeroid/server/node_modules/web3-core-requestmanager/lib/index.js:308:9
    at XMLHttpRequest.request.onreadystatechange (/home/ubuntu/projects/zeroid/server/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ubuntu/projects/zeroid/server/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/ubuntu/projects/zeroid/server/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/ubuntu/projects/zeroid/server/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/ubuntu/projects/zeroid/server/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by adi44** [comment]
@pawanlapits you might not be using the correct contract address or ABI. Pls ensure that you use correct contract address along with ABI

**Comment by pawanlapits** [comment]
@adi44  but how it working for writing data.

**Comment by pawanlapits** [comment]
@adi44   I am using correct address and abi

**Comment by adi44** [comment]
in that case look how much funds you have?

**Comment by pawanlapits** [comment]
@adi44   first of now, there is no need of funds while reading data from smart contract. I have sufficient funds by the way.

**Comment by wackerow** [comment]
@pawanlapits glad to see you're interested in smart contracts! This repo is dedicated to the ethereum.org website specifically... if you have questions about developing smart contracts try checking out the [Hardhat discord](https://discord.gg/xtrMGhmbfZ) or [CryptoDevs discord](https://discord.gg/Z9TA39m8Yu) to find some help. Closing this issues as it does not apply to this repo.
