### ISSUE TITLE
Migrate `TranslationBanner` component to Chakra UI

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8052]
This is part of our [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.

## Description
Migrate `src/components/TranslationBanner.tsx` from `emotion` styled components to `chakra`.

This component is used in any page that is not fully translated. For example, https://ethereum.org/es/layer-2/
![image](https://user-images.githubusercontent.com/468158/192541136-33722ef5-0b35-4948-b32f-14f2e92ab17e.png)

## Additional resources
Check our [epic](https://github.com/ethereum/ethereum-org-website/issues/6374) for more information & check our [migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md).

**Comment by Dhaiwat10** [comment]
Happy to take this on! @pettinarip

**Comment by pettinarip** [comment]
Thanks @Dhaiwat10!

**Comment by Dhaiwat10** [comment]
Hi @pettinarip, I'm unfortunately having some trouble trying to run the project locally. This is what I'm seeing when I run `yarn start`:

```
yarn run v1.22.18
$ gatsby develop
success compile gatsby files - 1.362s
info The following flags are active:
- FAST_DEV · Enable all experiments aimed at improving develop server start time.
- DEV_SSR · (Umbrella Issue (https://gatsby.dev/dev-ssr-feedback)) · Server Side Render (SSR) pages on full reloads
during develop. Helps you detect SSR bugs and fix them without needing to do full builds.
- PRESERVE_FILE_DOWNLOAD_CACHE · (Umbrella Issue (https://gatsby.dev/cache-clearing-feedback)) · Don't delete the
downloaded files cache when changing gatsby-node.js & gatsby-config.js files.

There are 2 other flags available that you might be interested in:
- PARALLEL_SOURCING · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/parallel-sourcing-feedback)) · Run all source
plugins at the same time instead of serially. For sites with multiple source plugins, this can speedup sourcing and
transforming considerably.
- DETECT_NODE_MUTATIONS · Diagnostic mode to log any attempts to mutate node directly. Helpful when debugging missing
data problems. See https://gatsby.dev/debugging-missing-data for more details.

success load gatsby config - 0.056s
warn Plugin gatsby-remark-reading-time is not compatible with your gatsby version 4.21.1 - It requires gatsby@^2.0.0
warn Plugin gatsby-transformer-gitinfo is not compatible with your gatsby version 4.21.1 - It requires gatsby@^2.0.15
warn Plugin gatsby-remark-reading-time is not compatible with your gatsby version 4.21.1 - It requires gatsby@^2.0.0
warn Plugin gatsby-transformer-gitinfo is not compatible with your gatsby version 4.21.1 - It requires gatsby@^2.0.15
success load plugins - 1.545s
success onPreInit - 0.004s
success initialize cache - 0.091s
success copy gatsby files - 0.091s
success Compiling Gatsby Functions - 0.120s
info [gatsby-theme-i18n]: Config file found at /Users/dhaiwat/code/ethereum-org-website/i18n/config.json
info Merged translations saved
info Contributors copied
success onPreBootstrap - 0.380s
success createSchemaCustomization - 0.031s
⠹ source and transform nodes
/Users/dhaiwat/code/ethereum-org-website/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: read ENOTCONN
    at tryReadStart (node:net:592:20)
    at Socket._read (node:net:603:5)
    at Socket.Readable.read (node:internal/streams/readable:487:10)
    at Socket.read (node:net:644:39)
    at new Socket (node:net:401:12)
    at Object.Socket (node:net:284:41)
    at createSocket (node:internal/child_process:327:14)
    at ChildProcess.spawn (node:internal/child_process:444:23)
    at Object.spawn (node:child_process:698:9)
    at Git._schedule (/Users/dhaiwat/code/ethereum-org-website/node_modules/simple-git/src/git.js:1406:41)
    at Git._run (/Users/dhaiwat/code/ethereum-org-website/node_modules/simple-git/src/git.js:1368:12)
    at Git.log (/Users/dhaiwat/code/ethereum-org-website/node_modules/simple-git/src/git.js:1266:19)
    at /Users/dhaiwat/code/ethereum-org-website/node_modules/simple-git/promise.js:67:24
    at new Promise (<anonymous>)
    at /Users/dhaiwat/code/ethereum-org-website/node_modules/simple-git/promise.js:58:20
    at runNextTicks (node:internal/process/task_queues:61:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  errno: -57,
  code: 'ENOTCONN',
  syscall: 'read'
}
```

After this, all my browser extensions crash too. Very weird. Am I missing something here? Thanks for your time

**Comment by pettinarip** [comment]
@Dhaiwat10 sorry for the delay. Do you still have this issue?

Not sure about it. Can you just add these configs to your local `.env` file?
```
GATSBY_BUILD_LANGS=en
IGNORE_CONTENT=**/docs,**/tutorials
```

That will build a smaller version of the website. Perhaps that fix the issue. LMK

**Comment by Dhaiwat10** [comment]
@pettinarip yeah happy to work on this but I see that someone else has already put in a PR for this (#8284). Should I still work on this then?

**Comment by pettinarip** [comment]
Uhmm ok, sorry about that @Dhaiwat10 not sure why @amit-ksh took this issue that was already assigned to you.

Well then, don't work on this please. Happy if you want to jump into that PR to review and share any feedback you might have.
