### ISSUE TITLE
Bug report: Blank page with cookies disabled

### ISSUE THREAD

**Issue by IstoraMandiri** [ethereum/ethereum-org-website#8725]
### Describe the bug

When visiting ethereum.org with cookies disabled, the static HTML loads and is visible for a few seconds as the page loads. As soon as the JavaScript is hydrated, the website goes completely blank and errors appear in the console (see below). The issue does not occur when cookies are enabled, or if Javascript is disabled.

This bug also occurs in the latest v4 gatsby-starger-blog, so I presume it's an upstream issue. 

### To reproduce

1. Disable use of cookies in browser
1. Go to 'https://ethereum.org'
1. Wait for page to load
1. See blank page

### Expected behavior

Website should be navigable when Javascript is enabled but cookies are disabled, or at least show a message explaining cookies are required.

### Screenshots

![image](https://user-images.githubusercontent.com/1696942/203687491-086740dd-d2bd-4983-8ac3-87462ce80eec.png)

### Console Log

```
react-dom.production.min.js:189 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://ethereum.org/app-a26f74aee63644920411.js:2:2225660
    at ri (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:163477)
    at Ss (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:183607)
    at is (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:175908)
    at Aa (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:116913)
    at https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:182409
    at ws (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:182414)
    at as (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:174911)
    at S (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:207637)
    at MessagePort.R (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:208169)
du @ react-dom.production.min.js:189
l.componentDidCatch.n.callback @ react-dom.production.min.js:190
Bl @ react-dom.production.min.js:144
ki @ react-dom.production.min.js:261
bi @ react-dom.production.min.js:260
yi @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
ws @ react-dom.production.min.js:281
is @ react-dom.production.min.js:273
Aa @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:283
ws @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:189 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://ethereum.org/app-a26f74aee63644920411.js:2:2225660
    at ri (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:163477)
    at Ss (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:183607)
    at is (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:175908)
    at Aa (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:116913)
    at https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:182409
    at ws (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:182414)
    at as (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:174911)
    at S (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:207637)
    at MessagePort.R (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:208169)
du @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
Bl @ react-dom.production.min.js:144
ki @ react-dom.production.min.js:262
bi @ react-dom.production.min.js:260
yi @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
ws @ react-dom.production.min.js:281
is @ react-dom.production.min.js:273
Aa @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:283
ws @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
react-dom.production.min.js:127 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://ethereum.org/app-a26f74aee63644920411.js:2:2225660
    at ri (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:163477)
    at Ss (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:183607)
    at is (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:175908)
    at Aa (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:116913)
    at https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:182409
    at ws (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:182414)
    at as (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:174911)
    at S (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:207637)
    at MessagePort.R (https://ethereum.org/framework-9b422d6655345ecc9bf5.js:2:208169)
Aa @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:283
ws @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
StatsBoxGrid.tsx:418 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at l (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9118)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9282
    at h (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1459)
    at Generator._invoke (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1212)
    at Generator.next (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1822)
    at n (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9614)
    at u (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9817)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9876
    at new Promise (<anonymous>)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9757
(anonymous) @ StatsBoxGrid.tsx:418
h @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
n @ asyncToGenerator.js:3
c @ asyncToGenerator.js:29
StatsBoxGrid.tsx:445 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at l (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9118)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9282
    at h (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1459)
    at Generator._invoke (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1212)
    at Generator.next (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1822)
    at n (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9614)
    at u (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9817)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9876
    at new Promise (<anonymous>)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9757
(anonymous) @ StatsBoxGrid.tsx:445
h @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
n @ asyncToGenerator.js:3
c @ asyncToGenerator.js:29
StatsBoxGrid.tsx:472 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at l (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9118)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9282
    at h (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1459)
    at Generator._invoke (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1212)
    at Generator.next (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:1822)
    at n (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9614)
    at u (https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9817)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9876
    at new Promise (<anonymous>)
    at https://ethereum.org/c59c8c01d3120326bab6a219bd3797ca8d167773-8e16292cc4fb7c915ad8.js:2:9757
(anonymous) @ StatsBoxGrid.tsx:472
h @ regeneratorRuntime.js:86
(anonymous) @ regeneratorRuntime.js:66
(anonymous) @ regeneratorRuntime.js:117
n @ asyncToGenerator.js:3
c @ asyncToGenerator.js:29
```

### Desktop (please complete the following information)

Brave Browser, Linux

**Comment by corwintines** [comment]
Interesting. Thanks for reporting @IstoraMandiri. I will bring this up in GitHub grooming with the team and report back.

**Comment by corwintines** [comment]
@pettinarip will be spiking on this when they have time. Not a very high priority issue at the moment, and as we may be migrating tech stacks this potentially won't be an issue in the future.

**Comment by nloureiro** [comment]
with the recent migration to NextJs it fixed this issue
